#!/usr/bin/env bash
#
# sync-primary-agents.sh — Sync custom primary agents to Claude Code
#
# Usage:
#   bash ~/.config/opencode/sync-primary-agents.sh
#
# What it does:
#   1. Reads primary agent .md files from ~/.config/opencode/agents/
#   2. Strips opencode-specific frontmatter fields (mode, permission)
#   3. Copies adapted files to ~/.claude/agents/
#
# Source of truth: ~/.config/opencode/agents/{alan-turing,grace-hopper,maestro}.md
# Claude Code target: ~/.claude/agents/{alan-turing,grace-hopper,maestro}.md

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { printf "${GREEN}[opencode]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[opencode]${NC} %s\n" "$*"; }
error() { printf "${RED}[opencode]${NC} %s\n" "$*" >&2; exit 1; }

SOURCE_DIR="$HOME/.config/opencode/agents"
TARGET_DIR="$HOME/.claude/agents"

# Primary agents tracked in git (not generated by setup.sh)
PRIMARY_AGENTS=(
  "alan-turing.md"
  "grace-hopper.md"
  "maestro.md"
)

mkdir -p "$TARGET_DIR"

synced=0
for agent in "${PRIMARY_AGENTS[@]}"; do
  src="$SOURCE_DIR/$agent"
  dst="$TARGET_DIR/$agent"

  if [[ ! -f "$src" ]]; then
    warn "Skipping $agent — not found at $src"
    continue
  fi

  # Strip opencode-specific frontmatter fields: mode, permission block
  # Claude Code uses the same format but does not support mode/permission
  awk '
    BEGIN { in_frontmatter=0; in_permission=0; frontmatter_done=0 }
    /^---$/ && !frontmatter_done {
      if (in_frontmatter) { frontmatter_done=1; in_frontmatter=0; print; next }
      else { in_frontmatter=1; print; next }
    }
    in_frontmatter && /^mode:/ { next }
    in_frontmatter && /^permission:/ { in_permission=1; next }
    in_frontmatter && in_permission && /^  / { next }
    in_frontmatter && in_permission { in_permission=0 }
    { print }
  ' "$src" > "$dst"

  info "Synced: $agent → $dst"
  ((synced++))
done

info "Done — $synced primary agent(s) synced to $TARGET_DIR"
info "Claude Code will load them automatically from ~/.claude/agents/"
