"""Guard test: no agent or skill may declare `model:` in its frontmatter.

Routing must flow through `oh-my-openagent.jsonc` (regenerated by `oc tier set`
from `tiers/*.yaml`). A persona-level `model:` would bypass the tier map.

See MADR 0009 — Tier-routing contract.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / "agents"
SKILLS_DIR = REPO_ROOT / "skills"

_FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---", re.DOTALL)
_MODEL_KEY_RE = re.compile(r"^model\s*:", re.MULTILINE)


def _frontmatter(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = _FRONTMATTER_RE.match(text)
    return match.group(1) if match else ""


@pytest.mark.parametrize("md_path", sorted(AGENTS_DIR.glob("*.md")))
def test_agent_has_no_model_override(md_path: Path) -> None:
    front = _frontmatter(md_path)
    assert not _MODEL_KEY_RE.search(front), (
        f"{md_path.name} declares `model:` in frontmatter — this bypasses the "
        f"tier map (oh-my-openagent.jsonc). Move the routing to tiers/*.yaml. "
        f"See docs/madr/0009-tier-routing-contract.md"
    )


@pytest.mark.parametrize("md_path", sorted(SKILLS_DIR.glob("*/SKILL.md")))
def test_skill_has_no_model_override(md_path: Path) -> None:
    front = _frontmatter(md_path)
    assert not _MODEL_KEY_RE.search(front), (
        f"{md_path.relative_to(REPO_ROOT)} declares `model:` in frontmatter — "
        f"this bypasses the tier map. See docs/madr/0009-tier-routing-contract.md"
    )
