model_list:
- model_name: gpt-4o-mini
  litellm_params:
    model: github_copilot/gpt-4o-mini
    max_retries: 0
- model_name: gemini-2.0-flash-001
  litellm_params:
    model: github_copilot/gemini-2.0-flash-001
    max_retries: 0
litellm_settings:
  callbacks:
  - prometheus
  drop_params:
  - reasoningSummary
  request_timeout: 120
  num_retries: 0
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: 6379
    namespace: litellm.cache
    ttl: 600
    max_connections: 50
router_settings:
  routing_strategy: simple-shuffle
  allowed_fails: 3
  cooldown_time: 5
  timeout: 120
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: true
  forward_client_headers_to_llm_api: true
  max_budget: 0
